import type { AdventureThemeDefinition } from '../types/adventureTypes';

export const defaultFantasyTheme: AdventureThemeDefinition = {
    id: 'classic-fantasy',
    title: '術式共鳴の迷宮譚',
    introText: '計算で術式を安定させ、4人パーティでダンジョンを攻略する冒険モードです。高位の計算ほど共鳴が強くなり、武器と仲間の一撃が重くなります。',
    badgeLabels: {
        bronze: 'ブロンズ',
        silver: 'シルバー',
        gold: 'ゴールド',
        platinum: 'プラチナ',
    },
    masteryLabel: 'プラチナマスター',
    partyMembers: [
        {
            id: 'warrior-m',
            characterLabel: '男戦士',
            jobName: '前衛剣士',
            initialWeaponName: '共鳴の剣',
        },
        {
            id: 'swordswoman-f',
            characterLabel: '女剣士',
            jobName: '蒼刃の剣士',
            initialWeaponName: '蒼晶の細剣',
        },
        {
            id: 'fighter-f',
            characterLabel: '女拳闘士',
            jobName: '閃拳の闘士',
            initialWeaponName: '断空グローブ',
        },
        {
            id: 'mage-m',
            characterLabel: '男魔法使い',
            jobName: '星詠みの術師',
            initialWeaponName: '導術の杖',
        },
    ],
    dungeons: [
        {
            id: 'stone-cave',
            name: '石ころの洞穴',
            description: '最初の訓練に向いた浅い洞穴。術式の基礎を確かめる場所です。',
            accentText: '低レベル向けの安定訓練ダンジョン',
            iconName: 'stone-cave.png',
            backgroundName: 'stone-cave-bg.jpg',
            enemies: {
                mobA: '小石スライム',
                mobB: '砕石コウモリ',
                mobC: '岩皮ゴブリン',
                boss: '石王ガーディアン',
                secret: '深層の石王影',
            },
            rewards: {
                materialName: '石片',
                treasureName: '石王の冠',
            },
        },
        {
            id: 'crystal-cavern',
            name: '水晶の洞窟',
            description: '反射する結晶が術式を増幅し、素早い正答が求められます。',
            accentText: '反射共鳴で威力が伸びやすい',
            iconName: 'crystal-cavern.png',
            backgroundName: 'crystal-cavern-bg.jpg',
            enemies: {
                mobA: '水晶スライム',
                mobB: 'きらめきハウンド',
                mobC: '断晶ランサー',
                boss: '水晶竜グラスレイ',
                secret: '深晶の残響体',
            },
            rewards: {
                materialName: '水晶片',
                treasureName: '水晶の宝珠',
            },
        },
        {
            id: 'amethyst-altar',
            name: '紫晶の祭壇',
            description: '濃い魔力が渦巻く祭壇跡。難度が少し上がる中級入口です。',
            accentText: '高位術式の練度確認に最適',
            iconName: 'amethyst-altar.png',
            backgroundName: 'amethyst-altar-bg.jpg',
            enemies: {
                mobA: '紫晶フロート',
                mobB: '祭壇の守り手',
                mobC: '幻碑ナイト',
                boss: '紫晶司祭アメジア',
                secret: '禁祀の結晶眼',
            },
            rewards: {
                materialName: '紫晶片',
                treasureName: '紫晶の聖杯',
            },
        },
        {
            id: 'yellow-corridor',
            name: '黄晶の回廊',
            description: '複雑な通路で連戦が続く回廊。安定した入力が重要になります。',
            accentText: '手数と安定性の両立を試す回廊',
            iconName: 'yellow-corridor.png',
            backgroundName: 'yellow-corridor-bg.jpg',
            enemies: {
                mobA: '黄晶ビー',
                mobB: '黄雷ウォーカー',
                mobC: '金紋の機兵',
                boss: '羅針の獅子王',
                secret: '迷光の羅針核',
            },
            rewards: {
                materialName: '黄晶片',
                treasureName: '黄晶の羅針盤',
            },
        },
        {
            id: 'garnet-crater',
            name: '柘榴石の火口',
            description: '火口の熱気で制御が乱れやすい高難度ダンジョンです。',
            accentText: '火力と正確性の両方が必要',
            iconName: 'garnet-crater.png',
            backgroundName: 'garnet-crater-bg.jpg',
            enemies: {
                mobA: '紅熱サラマンダー',
                mobB: '火紋の兵',
                mobC: '溶岩バジリスク',
                boss: '紅蓮侯ガルネット',
                secret: '火口の心核',
            },
            rewards: {
                materialName: '柘榴石片',
                treasureName: '紅蓮の勲章',
            },
        },
        {
            id: 'opal-mist',
            name: 'オパールの幻霧沼',
            description: '視界が揺らぐ霧の沼。割り算を含む複雑条件向きの戦場です。',
            accentText: '判断負荷の高い上級ダンジョン',
            iconName: 'opal-mist.png',
            backgroundName: 'opal-mist-bg.jpg',
            enemies: {
                mobA: '遊色ウィスプ',
                mobB: '霧影ハンター',
                mobC: '幻霧トード',
                boss: '虹彩の魔獣オパロス',
                secret: '虹霧の幻核',
            },
            rewards: {
                materialName: '遊色片',
                treasureName: '虹彩の鏡',
            },
        },
        {
            id: 'azure-ice-castle',
            name: '蒼玉の氷城',
            description: '冷気で一瞬の迷いが命取りになる終盤向けダンジョンです。',
            accentText: '速度と精度を高く求める氷城',
            iconName: 'azure-ice-castle.png',
            backgroundName: 'azure-ice-castle-bg.jpg',
            enemies: {
                mobA: '蒼氷スピリット',
                mobB: '霜剣ナイト',
                mobC: '凍冠ワイバーン',
                boss: '蒼王妃サファリア',
                secret: '零晶の王座守',
            },
            rewards: {
                materialName: '蒼玉片',
                treasureName: '蒼王のティアラ',
            },
        },
        {
            id: 'mithril-tower',
            name: 'ミスリルの塔',
            description: '全ての訓練の集大成となる高位ダンジョン。最高クラスの共鳴が必要です。',
            accentText: '最終訓練向けの高密度ダンジョン',
            iconName: 'mithril-tower.png',
            backgroundName: 'mithril-tower-bg.jpg',
            enemies: {
                mobA: '星鋼ビット',
                mobB: '白銀センチネル',
                mobC: '塔守りドラグーン',
                boss: '星鋼王ミスリウス',
                secret: '塔頂の真核体',
            },
            rewards: {
                materialName: 'ミスリル片',
                treasureName: '星鋼の印章',
            },
        },
    ],
};
