import type { AdventureTheme } from '../types/appTypes';

export const DEFAULT_ADVENTURE_THEME: AdventureTheme = {
    id: 'classic-fantasy',
    name: 'クラシックファンタジー',
    normalModeLabel: '通常モード',
    adventureModeLabel: '冒険モード',
    partyMembers: [
        {
            key: 'warriorMale',
            className: '男戦士',
            iconAsset: 'party-warrior-male.png',
            baseWeaponName: '旅立ちの剣',
        },
        {
            key: 'swordswoman',
            className: '女剣士',
            iconAsset: 'party-swordswoman.png',
            baseWeaponName: '旅立ちの細剣',
        },
        {
            key: 'fighterFemale',
            className: '女拳闘士',
            iconAsset: 'party-fighter-female.png',
            baseWeaponName: '旅立ちの手甲',
        },
        {
            key: 'wizardMale',
            className: '男魔法使い',
            iconAsset: 'party-wizard-male.png',
            baseWeaponName: '旅立ちの杖',
        },
    ],
    dungeons: [
        {
            id: 'stone-cave',
            order: 1,
            name: '石ころの洞穴',
            materialName: '石片',
            treasureName: '石王の冠',
            iconAsset: 'dungeon-stone-cave.png',
            backgroundAsset: 'bg-stone-cave.png',
            enemyNames: {
                mobA: 'ころ石スライム',
                mobB: '洞穴コボルト',
                mobC: '岩かぶとゴーレム',
                boss: '石王ゴルム',
                secret: '深層の巨石竜',
            },
            weaponNames: {
                warriorMale: '石砕きの剣',
                swordswoman: '岩穿ちの細剣',
                fighterFemale: '礫撃の手甲',
                wizardMale: '石核の杖',
            },
        },
        {
            id: 'crystal-cavern',
            order: 2,
            name: '水晶の洞窟',
            materialName: '水晶片',
            treasureName: '水晶の宝珠',
            iconAsset: 'dungeon-crystal-cavern.png',
            backgroundAsset: 'bg-crystal-cavern.png',
            enemyNames: {
                mobA: 'きらめきコウモリ',
                mobB: '晶角ウルフ',
                mobC: '鏡面ナイト',
                boss: '水晶の守護獣',
                secret: '透輝の魔晶王',
            },
            weaponNames: {
                warriorMale: '水晶刃ブレード',
                swordswoman: '輝晶レイピア',
                fighterFemale: '晶拳グローブ',
                wizardMale: '透明晶の杖',
            },
        },
        {
            id: 'amethyst-altar',
            order: 3,
            name: '紫晶の祭壇',
            materialName: '紫晶片',
            treasureName: '紫晶の聖杯',
            iconAsset: 'dungeon-amethyst-altar.png',
            backgroundAsset: 'bg-amethyst-altar.png',
            enemyNames: {
                mobA: '祭壇の影獣',
                mobB: '紫煙の呪兵',
                mobC: '幻紫の眼',
                boss: '紫晶司祭オルド',
                secret: '常闇の祭王',
            },
            weaponNames: {
                warriorMale: '紫晶大剣',
                swordswoman: '宵紫の細剣',
                fighterFemale: '紫雷の手甲',
                wizardMale: '夜晶の杖',
            },
        },
        {
            id: 'citrine-corridor',
            order: 4,
            name: '黄晶の回廊',
            materialName: '黄晶片',
            treasureName: '黄晶の羅針盤',
            iconAsset: 'dungeon-citrine-corridor.png',
            backgroundAsset: 'bg-citrine-corridor.png',
            enemyNames: {
                mobA: '砂金ビートル',
                mobB: '黄光ハウンド',
                mobC: '回廊の番兵',
                boss: '黄晶将オリオン',
                secret: '暁光の獅子王',
            },
            weaponNames: {
                warriorMale: '黄晶の軍剣',
                swordswoman: '日輪レイピア',
                fighterFemale: '閃拳ガントレット',
                wizardMale: '陽炎の杖',
            },
        },
        {
            id: 'garnet-crater',
            order: 5,
            name: '柘榴石の火口',
            materialName: '柘榴石片',
            treasureName: '紅蓮の勲章',
            iconAsset: 'dungeon-garnet-crater.png',
            backgroundAsset: 'bg-garnet-crater.png',
            enemyNames: {
                mobA: '火口サラマンダー',
                mobB: '紅炎オーク',
                mobC: '灼熱の巨兵',
                boss: '柘榴の火竜',
                secret: '紅蓮皇ヴォルガ',
            },
            weaponNames: {
                warriorMale: '紅蓮斬の剣',
                swordswoman: '緋炎フェンサー',
                fighterFemale: '爆炎の手甲',
                wizardMale: '火晶の長杖',
            },
        },
        {
            id: 'opal-marsh',
            order: 6,
            name: 'オパールの幻霧沼',
            materialName: '遊色片',
            treasureName: '虹彩の鏡',
            iconAsset: 'dungeon-opal-marsh.png',
            backgroundAsset: 'bg-opal-marsh.png',
            enemyNames: {
                mobA: '霧色フェアリー',
                mobB: '幻沼リザード',
                mobC: '遊色の幻騎士',
                boss: 'オパール妖妃',
                secret: '七彩の霧帝',
            },
            weaponNames: {
                warriorMale: '幻彩ブレード',
                swordswoman: '虹映の細剣',
                fighterFemale: '霞拳の手甲',
                wizardMale: '遊色の杖',
            },
        },
        {
            id: 'sapphire-castle',
            order: 7,
            name: '蒼玉の氷城',
            materialName: '蒼玉片',
            treasureName: '蒼王のティアラ',
            iconAsset: 'dungeon-sapphire-castle.png',
            backgroundAsset: 'bg-sapphire-castle.png',
            enemyNames: {
                mobA: '氷羽スピリット',
                mobB: '蒼氷ナイト',
                mobC: '凍城の守護像',
                boss: '蒼王グレイシア',
                secret: '絶零の氷皇',
            },
            weaponNames: {
                warriorMale: '蒼氷大剣',
                swordswoman: '氷華レイピア',
                fighterFemale: '凍拳ガントレット',
                wizardMale: '蒼霜の杖',
            },
        },
        {
            id: 'mythril-tower',
            order: 8,
            name: 'ミスリルの塔',
            materialName: 'ミスリル片',
            treasureName: '星鋼の印章',
            iconAsset: 'dungeon-mythril-tower.png',
            backgroundAsset: 'bg-mythril-tower.png',
            enemyNames: {
                mobA: '塔衛メタル',
                mobB: '星鋼ファントム',
                mobC: '白銀ガーディアン',
                boss: 'ミスリル機神',
                secret: '星鋼の天帝',
            },
            weaponNames: {
                warriorMale: '星鋼の剣',
                swordswoman: '銀星レイピア',
                fighterFemale: '天鋼の手甲',
                wizardMale: '流星の杖',
            },
        },
    ],
};
